### ISSUE TITLE
Chatbot key

### ISSUE THREAD

**Issue by tzt345** [maisans-maid/Mai#121]
> Initializing the client. Please wait...
 SUCCESS!  Loaded 165 commands!
 SUCCESS!  Loaded 7 event files!
Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (/rbd/pnpm-volume/39348e56-f62c-4e3f-aeda-547d299c43e0/node_modules/discord.js/src/client/websocket/WebSocketManager.js:133:26)
    at MaiClient.login (/rbd/pnpm-volume/39348e56-f62c-4e3f-aeda-547d299c43e0/node_modules/discord.js/src/client/Client.js:223:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  [Symbol(code)]: 'TOKEN_INVALID'
}
 SUCCESS!  Connected to MongoDB!
 ERR! ANISCHEDULE: Missing Data from Database.
No lists were found on the database. Please ignore this message if this is the first time setting the bot.

Help Plz

**Comment by kakarot-dev** [comment]
ur discordjs token is invalid

**Comment by kakarot-dev** [comment]
I mean ur discord bot token is invalid

**Comment by tzt345** [comment]
> I mean ur discord bot token is invalid

I put it the right token

**Comment by tzt345** [comment]
& I need the chatbot feature

**Comment by tzt345** [comment]
> > I mean ur discord bot token is invalid
> 
> I put it the right token

Oh nvm I was stupid
